[package]
name = "hajihujin/wasmer-web-terminal"
version = "0.1.0"
description = "Wasmer Web Terminal"

[dependencies]
"node/node" = "^18"

[[command]]
name = "server"
module = "node/node:node"
runner = "wasi"
annotations.wasi.main-args = ["index.js"]
